module.exports = {
  hello: 'hello，welcome to MIOT Extension development !',
  selfDefineScene: 'custom scene',
  timeSetting: 'time setting',
  countDownTime: 'countdown time',
  //设置页面
  battery: 'Battery',
  functionSettings: 'Function settings',
  noBatteryData: 'No Data',
  selfCheckReminder: 'Monthly Self-check Reminder',
  silence: 'Silence',
  selfCheck: 'Self-check',

  //首页
  logs: 'Logs',
  noLogs: 'No Logs',
  smartScene: 'Smart Scene',
  selfCheckRemindStr: 'Tip: We recommend that you conduct a self-check of the equipment',
  selfCheckRemindYesStr: 'Okay',
  homeRemindStr1: 'Natural gas trigger alarm',
  homeRemindStr2: 'Please check on your family.',
  homeRemindStr3: 'End of Sensor Life.',

  //事件
  workNormally: 'Work Normally',
  alarm: 'Gas Leak Alarm',
  deviceFailure: 'Device Failure',
  deviceEndOfLife: 'Sensor End of Life',
  deviceWarmUp: 'Sensor Warm-up',
  deviceSelfCheck: 'Sensor Self-check',
  analogueAlarm: 'Sensor Analog alarm',
  //蓝牙状态
  bleStr1: 'Searching for equipment.',
  bleStr2: 'Bluetooth is up and ready to search the device.',
  bleStr3: 'Bluetooth is not on, please check to turn on Bluetooth and try again.',
  bleStr4: 'Bluetooth is on.',
  bleStr5: 'Bluetooth connection disconnected.',
  bleStr6: 'Connected, click the "Start Self Check" button.',
  bleStr7: 'Being connected, please wait.',
  bleStr8: 'No connection, please return and try again.',
  bleStr9: 'disconnected',
  bleStr10: 'Connection failed, click back to try again',
  bleStr11: 'connected',
  bleBtnStr: 'Start Self Check',
  bleStr6Silence: 'Connected, click the "Silence" button.',

  isSuccess: 'Is there a beep?',
  yesStr: 'Yes',
  noStr: 'No',
  selfCheckSuccess: 'Self-check success',
  selfCheckFail: 'Self-check failure',
  selfCheckDone: 'Complete',
  selfCheckRetry: 'Retry',
  //消音
  silenceBtnStr: 'Silence',
  silenceSuccessStr: 'Silencing command sent.',
  silenceOkayStr: 'Okay',
};
