module.exports = {
  hello: '你好，欢迎加入 MIOT 扩展程序开发!',
  selfDefineScene: '自定义场景',
  timeSetting: '时间设置',
  countDownTime: '倒计时',
  //设置页面
  battery: '电池寿命',
  functionSettings: '功能设置',
  noBatteryData: '暂无数据',
  selfCheckReminder: '每月自检提醒',
  silence: '消音',
  selfCheck: '自检',
  //首页
  logs: '日志',
  noLogs: '暂无日志',
  smartScene: '智能场景',
  selfCheckRemindStr: '温馨提示：建议您进行设备自检',
  selfCheckRemindYesStr: '好',
  //事件
  workNormally: '工作正常',
  alarm: '燃气泄漏报警',
  deviceFailure: '设备故障',
  deviceEndOfLife: '传感器寿命到期',
  deviceWarmUp: '传感器预热',
  deviceSelfCheck: '设备自检',
  analogueAlarm: '模拟报警',
  //自检蓝牙状态
  bleStr1: '正在搜索设备',
  bleStr2: '蓝牙已开启，准备搜索设备',
  bleStr3: '蓝牙未开启，请检查开启蓝牙后再试',
  bleStr4: '蓝牙已开启',
  bleStr5: '蓝牙连接已断开',
  bleStr6: '已连接,请点击“开始自检”按钮',
  bleStr7: '正在连接，请稍候。。。',
  bleStr8: '未连接，请返回重试',
  bleStr9: '未连接',
  bleStr10: '连接失败，请点击返回重试',
  bleStr11: '连接中',
  bleBtnStr: '开始自检',
  isSuccess: '有蜂鸣声吗？',
  yesStr: '有',
  noStr: '没有',
  selfCheckSuccess: '自检成功',
  selfCheckFail: '自检失败',
  selfCheckDone: '完成',
  selfCheckRetry: '重试',

};

